version: '3.2'
services: 
  prom-pushgateway:
    image: prom/pushgateway
    ports: 
      - 9091:9091
  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus:/etc/prometheus:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
  app1:
    build: .
    ports:
      - "8080:8080"
    environment:
      - APP_INSTANCE=app1
      - APP_PUSH_GATEWAY=http://prom-pushgateway:9091
  app2:
    build: .
    ports:
      - "8081:8080"
    environment:
      - APP_INSTANCE=app2
      - APP_PUSH_GATEWAY=http://prom-pushgateway:9091

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./monitoring/grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=foobar
      - GF_USERS_ALLOW_SIGN_UP=false
  alertmanager:
    image: prom/alertmanager
    ports:
    - 9093:9093
    command:
    - --config.file=/etc/alertmanager/alertmanager.yml
    volumes:
    - ./monitoring/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro

  webhook:
    build:
      context: webhook
      args:
        goPackage: github.com/prometheus-community/prometheus-playground/alertmanager/webhook
        goVersion: 1.17
      cache_from:
      - golang:1.17
      - scratch
    ports:
    - 5001:5001